name: dio_log_sds
description: A plug-in that captures requests and views them within the
  application, providing functions such as request replication and JSON
  expansion
version: 5.0.0
homepage: https://github.com/HVLoc/dio_log_sds

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
